Fix pack stacking exploit
Sefiraat/Cultivation pull request #73
Opened 2023-12-10 14:00 UTC by Bunnky

This is a simple fix for Seed Pack stacking. If a player sets 2 packs to the same seed, they can be restacked, then used together to reproduce more drops than they should.

2023-12-10 20:25 UTC, J3fftw1 requested changes

2023-12-10 20:25 UTC, J3fftw1 commented on src/main/java/dev/sefiraat/cultivation/implementation/listeners/SeedPackListener.java
> +                if (packStack <= 1) {
We should negate this so the diff is less big

2023-12-11 11:15 UTC, J3fftw1 commented
I did review 👀

2023-12-11 11:17 UTC, Bunnky commented
> I did review 👀

apologies misclick! i think that is what you meant by negation #2574f5c

2023-12-11 11:18 UTC, J3fftw1 approved these changes
Lgtm

2023-12-11 11:33 UTC, Bunnky commented
After i had my coffee i realized the first change didnt make sense, it wanted more than 1 in a stack :P https://github.com/Sefiraat/Cultivation/pull/73/commits/4314dc5d6dabd02b48546456e6d30b00da7c1bda I physically tested as well

2024-01-15 18:53 UTC, merged